//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sending
    {
        public int Id { get; set; }
        public int Weight { get; set; }
        public int Volume { get; set; }
        public string Description { get; set; }
        public int ValuePrice { get; set; }
        public int PriceForSending { get; set; }
        public int CreatedBy { get; set; }
        public int SentById { get; set; }
        public int SentToId { get; set; }
        public int SendingTypeId { get; set; }
        public int TransportTypeId { get; set; }
        public int SentFromOfficeId { get; set; }
        public int SentToOfficeId { get; set; }
        public int SendingStatusId { get; set; }
        public Nullable<System.DateTime> DateOfSending { get; set; }
    
        public virtual PostOffice PostOffice { get; set; }
        public virtual PostOffice PostOffice1 { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual SendingType SendingType { get; set; }
        public virtual SendingStatus SendingStatus { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual TransportType TransportType { get; set; }
    }
}
